### ISSUE TITLE
nmin修改超过10的时候就会报错

### ISSUE THREAD

**Issue by gaoxuxu110** [KakaruHayate/ColorSplitter#4]
报错内容
`Traceback (most recent call last):
  File "H:\Deepfacelab\Voice\tools\ColorSplitter\splitter.py", line 46, in <module>
    labels = Cluster.__call__(embeds)
  File "H:\Deepfacelab\Voice\tools\ColorSplitter\modules\cluster.py", line 158, in __call__
    labels = self.cluster(X)
  File "H:\Deepfacelab\Voice\tools\ColorSplitter\modules\cluster.py", line 45, in __call__
    emb, num_of_spk = self.get_spec_embs(laplacian, oracle_num)
  File "H:\Deepfacelab\Voice\tools\ColorSplitter\modules\cluster.py", line 90, in get_spec_embs
    num_of_spk = np.argmax(lambda_gap_list) + self.min_num_spks
  File "H:\Deepfacelab\Voice\tools\ColorSplitter\env\lib\site-packages\numpy\core\fromnumeric.py", line 1229, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out, **kwds)
  File "H:\Deepfacelab\Voice\tools\ColorSplitter\env\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "H:\Deepfacelab\Voice\tools\ColorSplitter\env\lib\site-packages\numpy\core\fromnumeric.py", line 45, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence`

**Comment by gaoxuxu110** [comment]
问题解决了, 麻烦, 在cluster.py下把max_num_spks改大一点就好了

**Comment by KakaruHayate** [comment]
> 问题解决了, 麻烦, 在cluster.py下把max_num_spks改大一点就好了

并没有考虑到`max_num_spks`比较大的情况，一般来讲也没有这个需求

另外请确认正在正确的使用该工具（去划分单说话人的音色）而不是在把他当成声纹识别使用（它可以做到但是做的很不好）
