### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by gagangulyani** [KakaruHayate/ColorSplitter#5]
When i run the following command, i see an assertion error

```bash
python splitter.py --spk rishabh
Loaded the voice encoder model on cpu in 0.01 seconds.
Traceback (most recent call last):
  File "/Users/gagandeepsingh/Projects/ColorSplitter/splitter.py", line 44, in <module>
    labels = Cluster.__call__(embeds)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gagandeepsingh/Projects/ColorSplitter/modules/cluster.py", line 154, in __call__
    assert len(X.shape) == 2, 'Shape of input should be [N, C]'
AssertionError: Shape of input should be [N, C]
```
I have no idea what this means.

**Comment by KakaruHayate** [comment]
```
    - input
        - <speaker_name>
            - raw
                - wavs
                    - audio1.wav
                    - audio2.wav
                    - ...
```
1. Please check your file structure as shown above 
2. Delete the *. pkl file in the folder... \<speaker>\
